version: '3.6'

services:
  app:
    build: .
    command: npm run start
    environment:
      NODE_ENV: development
    ports:
      - '3000:3000'
    volumes:
      - .:/home/app
      - /home/app/node_modules
